### ISSUE TITLE
Update issue history dataset in Domo from issues in Github/Zenhub

### ISSUE THREAD

**Issue by BruceP99166** [openstax/organizational-agility#32]
# Description
Update Domo issue_history with data from Github/Zenhub

# Acceptance
* Today's issue data from Github/Zenhub appended to ghzh_issue_history

# Solution
Python script to read github/zenhub and create ghzh_history datasets in Domo.  

# Tests
- Fields included: organization_name, repo_name, pipeline_name, issue_title, issue_number, child_issue_numbers, issue_labels, issue_releases, issue_url, open_closed, issue_estimate, issue_is_epic, issue_is_pr, repo_id, batch_id, batch_run
- batch_id contains the current max batch_id + 1
- batch_run contains the update datetime and is the same for all of today's rows
- All issues and PRs are included for each repo except marker issues with '---' in title

# Tasks
- [x] Explore zenhub api
- [x] Refactor burnup dataflow
- [x] Create ghzh_history_issue in Domo
- [x] Include all issues in the openstax and cnx organizations
- [x] Change fieldnames to lower case.
- [x] Include PRs in update.  
- [x] Include child_issue_number to store child issues of epics. 
- [ ] Fix error causing "Update failed" popup
- [ ] Document the code
- [x] Productionize

**Comment by BruceP99166** [comment]
Domo json connector

BoardName = not needed
ListName = zenhub issues pipeline/name
CardName = github issues title
Label Names = github issues labels
Card ShortUrl = github issues url
Card Closed = not used
Points = zenhub issues estimate/value
BoardId = not needed
ListId = not available
CardId = github issues node_id
Join = "y"
BatchId = not available
BatchLastRun = generated

**Comment by BruceP99166** [comment]
Zenhub api for board info does not return closed issues therefore cannot get estimates for them.
Can request issue by issue but this will exceed api rate limit.

Solution for closed issues is to look up in ghzh_issue_history the estimate when the issue was last open.

If an issue is opened and closed in one day, it may never have an estimate in ghzh_issue_history.  Then will set estimate to None.

**Comment by BruceP99166** [comment]
GhZhToDomo 2019-01-02 15:36
Failed at 53:21 elapsed time with http 408
Request URL: https://api.zenhub.io/p1/reports/release/5bbe1c639c41fb34bb46ae07/issues?access_token=aea0232386bd74d064d4403c7f7dcf7c78d826763720efe074ea0231b9a445c3a434512da822e6b0

Rerunning with status retry specified for http session
retry = Retry(connect=3, status=3, status_forcelist=([408]), backoff_factor=0.5)

**Comment by BruceP99166** [comment]
Successfully created ghzh_issue from GitHub/ZenHub issues but unable to use it as input to a dataflow in Domo.

Try exporting GH issues to csv and creating ghzh ds from that to reproduce error.

**Comment by BruceP99166** [comment]
ds ghzh_batchid does not seem to be updating, so workflow GhZh Update Issue History is not triggered.

**Comment by BruceP99166** [comment]
Set up dataflows to update ghzh_issue_history from ghzh_issue1-5

Wrote dataflow [GhZh Concatenate Issue] to concatenate GhZhToDomo1-5.  Added command line parm to GhZhToDomo.py to allow specifying the dsid of the issue file to be created.
Inputs
- GhZhToDomo1: repos 0 to 50 > ghzh_issue1 6cd67468-4d9e-41cf-a135-832226a3f012: 5256 issues
- GhZhToDomo2: repos 51 to 100 > ghzh_issue2 197b88a0-f8b3-4d97-af8d-27231b5f7f3c: 1298 issues
- GhZhToDomo3: repos 101 to 150 > ghzh_issue3 a9f405b3-2958-4274-a93c-7ba3d045f543: 265 issues
- GhZhToDomo4: repos 151 to 200 > ghzh_issue4 888d6fb1-3b13-4626-b417-a6a86c1b1296: 1693 issues
- GhZhToDomo5: repos 200 to 250 > ghzh_issue5 6e7d1c1f-f6ce-4146-afc3-95d8c4131add: 14 issues
Output
- ghzh_issue bc2cb370-249c-4401-97b1-5471008a97ec

[GhZh Concatenate Issue]
Input
- ghzh_issue_history c88c9563-4be9-4acf-917e-e1f5c8b8fb59
- ghzh_batchid 4e88a075-3fd1-4e57-9771-91d94ba90b42
- ghzh_issue bc2cb370-249c-4401-97b1-5471008a97ec

Output
- ghzh_issue_history c88c9563-4be9-4acf-917e-e1f5c8b8fb59
- ghzh_batchid 4e88a075-3fd1-4e57-9771-91d94ba90b42

**Comment by BruceP99166** [comment]
GhZh Update Issue History does not increment ghzh_batchid

**Comment by BruceP99166** [comment]
Running update with 3 repo subsets
GhZhToDomo.py
GhZhToDomo1: repos 0 to 10 > ghzh_issue1 6cd67468-4d9e-41cf-a135-832226a3f012: issues processed=3369 output=3368
    Failed to access ghzh_batchid
GhZhToDomo2: repos 11 to 100 > ghzh_issue2 197b88a0-f8b3-4d97-af8d-27231b5f7f3c: issues processed= output= 
GhZhToDomo3: repos 101 to 300- > ghzh_issue3 a9f405b3-2958-4274-a93c-7ba3d045f543: issues processed= output= 
All ran successfully but output less issues than processed.

[GhZh Update Issue History]
Input
GhZhToDomo1
GhZhToDomo2
GhZhToDomo3
ghzh_issue_history c88c9563-4be9-4acf-917e-e1f5c8b8fb59 issues=42892
ghzh_batchid 4e88a075-3fd1-4e57-9771-91d94ba90b42 value=
Output
ghzh_issue_history c88c9563-4be9-4acf-917e-e1f5c8b8fb59 issues=
ghzh_batchid 4e88a075-3fd1-4e57-9771-91d94ba90b42 value=

**Comment by BruceP99166** [comment]
*Output issue ds fails as input*
Created ghzh_issue_debug_190207 with dummy issue names and urls to send to Will Evans for debug.

**Comment by BruceP99166** [comment]
Removing bad records from ghzh_issue_history
Run [GhZh Issue History Remove Bad Records] to select issues with batchId=55
Input 
ghzh_issue_history c88c9563-4be9-4acf-917e-e1f5c8b8fb59 rows=77247
Output
ghzh_issue_history 69a663c6-b666-4ccc-a2d7-a84d0a8dbbee rows=8578

Run [GhZh Update Issue History] to create ghzh_issue_history with issue rows from 2/8 appended
Input
ghzh_issue_history 69a663c6-b666-4ccc-a2d7-a84d0a8dbbee rows=8578

**Comment by BruceP99166** [comment]
After adding PRs, issue2 ds has 16000 rows; fails as dataflow input.

Testing to see what ds size will work.

**Comment by BruceP99166** [comment]
**authentication**
Fixed

**Output issue ds fails as input**
Implemented csv fix.  
Trying with all repos.

**Comment by BruceP99166** [comment]
Issue moved to [openstax/domo #60](https://github.com/openstax/domo/issues/60) via [**ZenHub**](https://www.zenhub.com/)
